version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    commit-message:
      prefix: "[Dependabot] "
      include: "scope"