name: xivr
description: X Image Viewer Rifle - wrapper for *sxiv with nice features
version: 1.2.0
repository: https://github.com/royarg02/xivr

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.5.0
  file: ^7.0.0
  platform: ^3.1.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8
