name: xivr
description: X Image Viewer Rifle - wrapper for *sxiv with nice features
version: 1.1.1
repository: https://github.com/royarg02/xivr

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0
  file: ^7.0.0
  platform: ^3.1.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
